openapi: 3.0.0
info:
  title: Phase One
  description: Phase One
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Admin
  - name: Admin > HouseCategory
  - name: Admin > Feature
  - name: Admin > House
  - name: Admin > JobCategory
  - name: Admin > Job
  - name: Client
paths:
  /admin/house/category:
    post:
      tags:
        - Admin > HouseCategory
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: category 1
                description:
                  type: string
                  example: description 1
                order_level:
                  type: string
                parent_id:
                  type: string
                status:
                  type: integer
                  example: '0'
                meta_title:
                  type: string
                  example: meta title 1
                meta_description:
                  type: string
                  example: meta description 1
                meta_keyword:
                  type: string
                  example: meta keyword 1
                icon:
                  type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/house/category/1:
    post:
      tags:
        - Admin > HouseCategory
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: category edit
                description:
                  type: string
                  example: description edit
                order_level:
                  type: integer
                  example: '2'
                parent_id:
                  type: string
                status:
                  type: integer
                  example: '1'
                meta_title:
                  type: string
                  example: meta title edit
                meta_description:
                  type: string
                  example: meta description edit
                meta_keyword:
                  type: string
                  example: meta keyboard edit
                icon:
                  type: string
                _method:
                  type: string
                  example: patch
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > JobCategory
      summary: show
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > JobCategory
      summary: destroy
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/house/category/:
    get:
      tags:
        - Admin > HouseCategory
      summary: index
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/house/feature:
    post:
      tags:
        - Admin > Feature
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: title 1
                description:
                  type: string
                  example: description 1
                category_id:
                  type: integer
                  example: '1'
                address:
                  type: string
                  example: address 1
                status:
                  type: integer
                  example: '0'
                image:
                  type: string
                  format: binary
                price:
                  type: integer
                  example: '99999'
                is_negotiable:
                  type: integer
                  example: '0'
                from_date:
                  type: string
                  example: '2022-01-01'
                to_date:
                  type: string
                  example: '2022-12-30'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Feature
      summary: index
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/house/feature/1:
    get:
      tags:
        - Admin > Feature
      summary: show
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Feature
      summary: destroy
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Admin > Feature
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: title 1
                description:
                  type: string
                  example: description 1
                category_id:
                  type: integer
                  example: '1'
                address:
                  type: string
                  example: address 1
                status:
                  type: integer
                  example: '0'
                image:
                  type: string
                  format: binary
                price:
                  type: integer
                  example: '99999'
                is_negotiable:
                  type: integer
                  example: '0'
                from_date:
                  type: string
                  example: '2022-01-01'
                to_date:
                  type: string
                  example: '2022-12-30'
                _method:
                  type: string
                  example: patch
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/house:
    post:
      tags:
        - Admin > House
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: title 1
                description:
                  type: string
                  example: description 1
                category_id:
                  type: integer
                  example: '1'
                address:
                  type: string
                  example: address 1
                status:
                  type: integer
                  example: '0'
                image:
                  type: string
                  format: binary
                price:
                  type: integer
                  example: '99999'
                is_negotiable:
                  type: integer
                  example: '0'
                from_date:
                  type: string
                  example: '2022-01-01'
                to_date:
                  type: string
                  example: '2022-12-30'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/house/:
    get:
      tags:
        - Admin > House
      summary: index
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/house/1:
    get:
      tags:
        - Admin > Job
      summary: show
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Job
      summary: destroy
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Admin > Job
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: title 1
                description:
                  type: string
                  example: description 1
                category_id:
                  type: integer
                  example: '1'
                address:
                  type: string
                  example: address 1
                status:
                  type: integer
                  example: '0'
                image:
                  type: string
                  format: binary
                price:
                  type: integer
                  example: '99999'
                is_negotiable:
                  type: integer
                  example: '0'
                from_date:
                  type: string
                  example: '2022-01-01'
                to_date:
                  type: string
                  example: '2022-12-30'
                _method:
                  type: string
                  example: patch
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/job/category:
    post:
      tags:
        - Admin > JobCategory
      summary: store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: category 1
                description: description 1
                order_level: ''
                parent_id: ''
                status: '0'
                meta_title: meta_title 1
                meta_description: meta_description 1
                meta_keyword:
                  - keyword 1
                  - keyword 2
                  - keyword 3
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/job/category/1:
    post:
      tags:
        - Admin > JobCategory
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: category edit
                description:
                  type: string
                  example: description edit
                order_level:
                  type: integer
                  example: '2'
                parent_id:
                  type: string
                status:
                  type: integer
                  example: '1'
                meta_title:
                  type: string
                  example: meta title edit
                meta_description:
                  type: string
                  example: meta description edit
                meta_keyword:
                  type: string
                  example: meta keyboard edit
                icon:
                  type: string
                _method:
                  type: string
                  example: patch
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/job/category/:
    get:
      tags:
        - Admin > JobCategory
      summary: index
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/house/job:
    post:
      tags:
        - Admin > Job
      summary: store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: |-
                {
                    "id": "",
                    "availability": 1,
                    "sku": "sku1",
                    "stock": 0,
                    "base_price": 101,
                    "selected_attribute": [
                        {
                            "id": "",
                            "attribute_id": 4,
                            "value_id": 13
                        },
                        {
                            "id": "",
                            "attribute_id": 5,
                            "value_id": 15
                        }
                    ],
                    "quantity": {
                        "1-10": 101,
                        "11-22": 51
                    }
                },
                {
                    "id": "",
                    "availability": 1,
                    "sku": "sku2",
                    "stock": 0,
                    "base_price": 201,
                    "selected_attribute": [
                        {
                            "id": "",
                            "attribute_id": 4,
                            "value_id": 14
                        },
                        {
                            "id": "",
                            "attribute_id": 5,
                            "value_id": 16
                        }
                    ],
                    "quantity": {
                        "1-10": 201,
                        "11-22": 151
                    }
                } 
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Job
      summary: index
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/login:
    post:
      tags:
        - Admin
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@admin.com
                password:
                  type: string
                  example: asdasdasd
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /admin/logout:
    get:
      tags:
        - Admin
      summary: logout
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/login:
    post:
      tags:
        - Client
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@user.com
                password:
                  type: string
                  example: asdasdasd
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/register:
    post:
      tags:
        - Client
      summary: register
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@user.com
                password:
                  type: string
                  example: asdasdasd
                name:
                  type: string
                  example: hello world
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/logout:
    get:
      tags:
        - Client
      summary: logout
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: X-Requested-With
          in: header
          schema:
            type: string
          example: XMLHttpRequest
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
